<?php

/**
 * Implements hook_page_attachments_alter().
 */
function quoter_page_attachments_alter(array &$attachments) {
  // Use the dev library if we're developing locally.
  if (in_array('quoter/react_app', $attachments['#attached']['library']) && file_exists(__DIR__ . '/js/dist_dev')) {
    $index = array_search('quoter/react_app', $attachments['#attached']['library']);
    $attachments['#attached']['library'][$index] = 'quoter/react_app_dev';
  }
}
